openapi: 3.0.0
servers: []
#  - url : 'http://localhost:8080'
info:
  description: This is an application for booking camp sites that allows clients to book the place.
  version: "1.0.0"
  title: Booking camp sites API
  contact:
    email: hhchang1234@gmail.com

paths:
  /health:
    get:
      operationId: app.health
      responses:
        '200':
          description: Service is running
  /book/make_reservation:
    get:
      summary: gets reservation details
      operationId: app.get_book_campsite
      description: Gets book and payment details statistics
      parameters:
        - name: index
          in: query
          description: Gets the reservation at the index in the event store
          schema:
            type: integer
            example: 100
      responses:
        "200":
          description: Successfully returned a reservation event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Book'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /book/payments:
    get:
      summary: gets a payment from history
      operationId: app.get_payment
      description: gets a payment from the event store
      parameters:
        - name: index
          in: query
          description: Gets the payment at the index in the event store
          schema:
            type: integer
            example: 100
      responses:
        "200":
          description: Successfully returned a payment event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Payment"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    Book:
      type: object
      required:
        - book_id
        - client_id
        - campsite
        - number_of_guests
        - timestamp
        # - trace_id
      properties:
        book_id:
          type: string
          format: uuid
        client_id:
          type: string
          format: uuid
        campsite:
          type: string
        number_of_guests:
          type: integer
        timestamp:
          type: string
          format: date-time
        # trace_id:
        #   type: string
        #   format: uuid
    Payment:
      type: object
      required:
        - payment_id
        - client_id
        - campsite
        - number_of_guests
        - timestamp
        # - trace_id
      properties:
        payment_id:
          type: string
          format: uuid
        client_id:
          type: string
          format: uuid
        campsite:
          type: string
        number_of_guests:
          type: integer
        timestamp:
          type: string
          format: date-time
        # trace_id:
        #   type: string
        #   format: uuid
